apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service-green
  labels:
    app: notification-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green
    spec:
      containers:
        - name: notification-service
          image: 405894865394.dkr.ecr.us-east-1.amazonaws.com/notification:latest
          ports:
            - containerPort: 3000
