apiVersion: apps/v1
kind: Deployment

metadata:
  name: appointment-scheduling-blue
  labels:
    app: appointment-scheduling
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduling
      version: blue
  template:
    metadata:
      labels:
        app: appointment-scheduling
        version: blue
    spec:
      containers:
        - name: appointment-scheduling
          image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/appointment-scheduling:<unique-tag>
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-host
                  key: MYSQL_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-db-appointment
                  key: MYSQL_DATABASE_APPOINTMENT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: MYSQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-port
                  key: MYSQL_PORT
          ports:
            - containerPort: 4002
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        

