apiVersion: apps/v1
kind: Deployment

metadata:
  name: file-handler-blue
  labels:
    app: file-handler
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-handler
      version: blue
  template:
    metadata:
      labels:
        app: file-handler
        version: blue
    spec:
      containers:
        - name: file-handler
          image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/file-handler:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-host
                  key: MYSQL_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: MYSQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-port
                  key: MYSQL_PORT
          ports:
            - containerPort: 4001
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

