apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-test-runner
  namespace: medi-track-blue
spec:
  schedule: "0 * * * *"  # Run every hour
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: medi-track-gateway
            image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:<unique-tag>
            ommand: ["npm","run", "test:e2e"]
          restartPolicy: OnFailure
#           volumes:
#           - name: test-volume
#             configMap:
#               name: test-files
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: test-files
# data:
#   package.json: |
#     {
#       "name": "test-runner",
#       "scripts": {
#         "test": "jest"
#       },
#       "dependencies": {
#         "jest": "^29.0.0",
#         "@nestjs/testing": "^10.0.0"
#       }
#     }
#   jest.config.js: |
#     module.exports = {
#       moduleFileExtensions: ['js', 'json', 'ts'],
#       rootDir: '.',
#       testEnvironment: 'node',
#       testRegex: '.test.ts$',
#       transform: {
#         '^.+\\.(t|j)s$': 'ts-jest'
#       }
#     }