apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-test-runner
  namespace: medi-track-blue
spec:
  schedule: "0 * * * *" 
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: medi-track-gateway
              image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:<unique-tag>
              command: ["npm","run", "test:e2e"]
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: mysql-host
                      key: MYSQL_HOST
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-db
                      key: MYSQL_DATABASE
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: mysql-username
                      key: MYSQL_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-password
                      key: MYSQL_PASSWORD
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: mysql-port
                      key: MYSQL_PORT
                - name: PATIENT_RECORD_HOST
                  valueFrom:
                    secretKeyRef:
                      name: patient-record-host
                      key: PATIENT_RECORD_HOST
                - name: UPLOADER_HOST
                  valueFrom:
                    secretKeyRef:
                      name: file-handler-host
                      key: FILE_HANDLER_HOST
                - name: APPOINTMENTS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: appointment-host
                      key: APPOINTMENT_HOST
                - name: NOTIFICATIONS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: notification-host
                      key: NOTIFICATION_HOST
          restartPolicy: OnFailure

#           volumes:
#           - name: test-volume
#             configMap:
#               name: test-files
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: test-files
# data:
#   package.json: |
#     {
#       "name": "test-runner",
#       "scripts": {
#         "test": "jest"
#       },
#       "dependencies": {
#         "jest": "^29.0.0",
#         "@nestjs/testing": "^10.0.0"
#       }
#     }
#   jest.config.js: |
#     module.exports = {
#       moduleFileExtensions: ['js', 'json', 'ts'],
#       rootDir: '.',
#       testEnvironment: 'node',
#       testRegex: '.test.ts$',
#       transform: {
#         '^.+\\.(t|j)s$': 'ts-jest'
#       }
#     }