apiVersion: apps/v1
kind: Deployment

metadata:
  name: patient-record-blue
  labels:
    app: patient-record
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record
      version: blue
  template:
    metadata:
      labels:
        app: patient-record
        version: blue
    spec:
      containers:
        - name: patient-record-service
          image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/patient-record-service:<unique-tag>
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-host
                  key: MYSQL_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-db-patient-record
                  key: MYSQL_DATABASE_PATIENT_RECORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: MYSQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-port
                  key: MYSQL_PORT
            - name: PATIENT_RECORD_HOST
              valueFrom:
                secretKeyRef:
                  name: patient-record-host
                  key: PATIENT_RECORD_HOST
            - name: UPLOADER_HOST
              valueFrom:
                secretKeyRef:
                  name: file-handler-host
                  key: FILE_HANDLER_HOST
            - name: APPOINTMENTS_HOST
              valueFrom:
                secretKeyRef:
                  name: appointment-host
                  key: APPOINTMENT_HOST
            - name: NOTIFICATIONS_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-host
                  key: NOTIFICATION_HOST
          ports:
            - containerPort: 4000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
