version: 0.2

phases:
  pre_build:
    commands: 
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 405894865394.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t notification -f ./notification-service/Dockerfile ./notification-service
      - docker tag notification:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/notification:latest

      - docker build -t medi-track-gateway -f ./medi-track-2417924-20240485/Dockerfile ./medi-track-2417924-20240485
      - docker tag medi-track-gateway:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:latest
    
      - docker build -t patient-record-service -f ./patient-record-service/Dockerfile ./patient-record-service
      - docker tag patient-record-service:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/patient-record-service:latest

      - docker build -t file-handler -f ./file-handler/Dockerfile ./file-handler
      - docker tag file-handler:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/file-handler:latest

      - docker build -t appointment-scheduling -f ./appointment-scheduling-service/Dockerfile ./appointment-scheduling-service
      - docker tag appointment-scheduling-service:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/appointment-scheduling-service:latest
  post_build: 
    commands:
      - docker push 405894865394.dkr.ecr.us-east-1.amazonaws.com/notification:latest
      - docker push 405894865394.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:latest
      - docker push 405894865394.dkr.ecr.us-east-1.amazonaws.com/patient-record-service:latest