version: 0.2

phases:
  pre_build:
    commands: 
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 405894865394.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t notification -f ./notification-service/Dockerfile ./notification-service
      - docker tag notification:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/notification:latest

      - docker build -t medi-track-gateway -f ./medi-track-2417924-20240485/Dockerfile ./medi-track-gateway
      - docker tag medi-track-gateway:latest 405894865394.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:latest
  post_build: 
    commands:
      - docker push 405894865394.dkr.ecr.us-east-1.amazonaws.com/notification:latest
      - docker push 405894865394.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:latest