apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: medi-track-blue
  name: deployer-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
