apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medi-track-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nest.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: medi-track-gateway
            port:
              number: 80
