apiVersion: apps/v1
kind: Deployment

metadata:
  name: medi-track-gateway-green
  labels:
    app: medi-track-gateway
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medi-track-gateway
      version: green
  template:
    metadata:
      labels:
        app: medi-track-gateway
        version: green
    spec:
      containers:
        - name: medi-track-gateway
          image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:<unique-tag>
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-host
                  key: MYSQL_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: MYSQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-port
                  key: MYSQL_PORT
            - name: PATIENT_RECORD_HOST
              valueFrom:
                secretKeyRef:
                  name: patient-record-host
                  key: PATIENT_RECORD_HOST
            - name: UPLOADER_HOST
              valueFrom:
                secretKeyRef:
                  name: file-handler-host
                  key: FILE_HANDLER_HOST
            - name: APPOINTMENTS_HOST
              valueFrom:
                secretKeyRef:
                  name: appointment-host
                  key: APPOINTMENT_HOST
            - name: NOTIFICATIONS_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-host
                  key: NOTIFICATION_HOST
          ports:
            - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        

