apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service-green
  labels:
    app: notification-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green
    spec:
      containers:
        - name: notification
          image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/notification:<unique-tag>
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-host
                  key: MYSQL_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: MYSQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-s3-region
                  key: AWS_S3_REGION
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-port
                  key: MYSQL_PORT
          ports:
            - containerPort: 4003
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0