apiVersion: apps/v1
kind: Deployment

metadata:
  name: patient-record-green
  labels:
    app: patient-record
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record
      version: green
  template:
    metadata:
      labels:
        app: patient-record
        version: green
    spec:
      containers:
        - name: patient-record-service
          image: 061051254585.dkr.ecr.us-east-1.amazonaws.com/patient-record-service:<unique-tag>
          imagePullPolicy: IfNotPresent
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-host
                key: MYSQL_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-db
                key: MYSQL_DATABASE
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-username
                key: MYSQL_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: MYSQL_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: mysql-port
                key: MYSQL_PORT
          ports:
            - containerPort: 4000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0