apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: medi-track-blue
  region: us-east-1
  labels:
    app: medi-track
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medi-track
      version: blue
  template:
    metadata:
      labels:
        app: patient-service
        version: blue
    spec:
      containers:
        - name: patient-service
          image: <your-blue-version-image>
          ports:
            - containerPort: 3000
nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
