apiVersion: apps/v1
kind: Deployment

metadata:
  name: medi-track-green
  labels:
    app: medi-track
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medi-track
      version: green
  template:
    metadata:
      labels:
        app: medi-track
        version: green
    spec:
      containers:
        - name: medi-track
          image: 405894865394.dkr.ecr.us-east-1.amazonaws.com/medi-track-gateway:latest
          ports:
            - containerPort: 3000

