# medi-track-gateway-service.yaml
apiVersion: v1
kind: Service

metadata:
  name: medi-track-gateway
spec:
  selector:
    app: medi-track-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4001
  type: ClusterIP